apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 256079618386.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-test:v0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
